module.exports = {
    teams: [`ARI`, `ATL`, `BAL`, `BUF`, `CAR`, `CHI`, `CIN`, `CLE`, `DAL`, `DEN`, `DET`, `GB`, `HOU`, `IND`, `JAX`, `KC`, `LAC`, `LA`, `MIA`, `MIN`, `NE`, `NO`, `NYG`, `NYJ`, `OAK`, `PHI`, `PIT`, `SEA`, `SF`, `TB`, `TEN`, `WAS`, `UNK`],
    teamMapping: [
        { abbreviation: `ARI`, id: 76 },
        { abbreviation: `ATL`, id: 68 },
        { abbreviation: `BAL`, id: 56 },
        { abbreviation: `BUF`, id: 48 },
        { abbreviation: `CAR`, id: 69 },
        { abbreviation: `CHI`, id: 60 },
        { abbreviation: `CIN`, id: 57 },
        { abbreviation: `CLE`, id: 58 },
        { abbreviation: `DAL`, id: 52 },
        { abbreviation: `DEN`, id: 72 },
        { abbreviation: `DET`, id: 61 },
        { abbreviation: `GB`, id: 62 },
        { abbreviation: `HOU`, id: 64 },
        { abbreviation: `IND`, id: 65 },
        { abbreviation: `JAX`, id: 66 },
        { abbreviation: `KC`, id: 73 },
        { abbreviation: `LAC`, id: 75 },
        { abbreviation: `LA`, id: 77 },
        { abbreviation: `MIA`, id: 49 },
        { abbreviation: `MIN`, id: 63 },
        { abbreviation: `NE`, id: 50 },
        { abbreviation: `NO`, id: 70 },
        { abbreviation: `NYG`, id: 53 },
        { abbreviation: `NYJ`, id: 51 },
        { abbreviation: `OAK`, id: 74 },
        { abbreviation: `PHI`, id: 54 },
        { abbreviation: `PIT`, id: 59 },
        { abbreviation: `SEA`, id: 79 },
        { abbreviation: `SF`, id: 78 },
        { abbreviation: `TB`, id: 71 },
        { abbreviation: `TEN`, id: 67 },
        { abbreviation: `WAS`, id: 55 },
        { abbreviation: `UNK`, id: 01 }
    ]
}