export default {
  rosterPositions: [
    { id: 0, name: 'QB' },
    { id: 1, name: 'RB' },
    { id: 2, name: 'WR' },
    { id: 3, name: 'TE' },
    { id: 4, name: 'K' },
    // { id: 5, name: 'D' },
    { id: 5, name: 'RB/WR' },
    { id: 6, name: 'Flex' },
    { id: 7, name: 'Super Flex' },
  ],
  orderOf: [0, 1, 2, 8, 6, 7, 3, 4, 5],
  positionMap: [[0], [1], [2], [3], [4], [1, 2], [1, 2, 3], [0, 1, 2, 3]],
  maxOfPosition: [3, 5, 5, 3, 3],
  orderOfDescription: [
    'QB',
    'RB',
    'WR',
    'Super Flex',
    'RB/WR',
    'Flex',
    'TE',
    'K',
    'D',
  ],
  positionArray: ['QB', 'RB', 'WR', 'TE', 'K'],
};
