export default {
  buckets: ['passing', 'rushing', 'receiving', 'fumble', 'fieldGoal'],
  passing: [
    'touchdowns',
    'yards',
    'interceptions',
    'attempts',
    'completions',
    'twoPointMade',
    'plays20Plus',
    'plays40Plus',
  ],
  rushing: [
    'attempts',
    'yards',
    'touchdowns',
    'plays20Plus',
    'plays40Plus',
    'fumbles',
    'twoPointMade',
  ],
  receiving: [
    'targets',
    'receptions',
    'yards',
    'touchdowns',
    'plays20Plus',
    'plays40Plus',
    'fumbles',
    'twoPointMade',
  ],
  fumble: ['fumblesLost'],
  fieldGoal: [
    'made1_19',
    'made20_29',
    'made30_39',
    'made40_49',
    'made50Plus',
    'extraPointMade',
  ],
  defaultScores: {
    passing: {
      touchdowns: 4,
      yards: 0.04,
      interceptions: -2,
      attempts: 0,
      completions: 0,
      twoPointMade: 2,
      plays20Plus: 0,
      plays40Plus: 0,
    },
    rushing: {
      attempts: 0,
      yards: 0.1,
      touchdowns: 6,
      plays20Plus: 0,
      plays40Plus: 0,
      fumbles: -2,
      twoPointMade: 2,
    },
    receiving: {
      targets: 0,
      receptions: 0,
      yards: 0.1,
      touchdowns: 6,
      plays20Plus: 0,
      plays40Plus: 0,
      fumbles: -2,
      twoPointMade: 0,
    },
    fumble: {
      fumblesLost: -2,
    },
    fieldGoal: {
      made1_19: 2,
      made20_29: 2,
      made30_39: 2,
      made40_49: 3,
      made50Plus: 5,
      extraPointMade: 1,
    },
  },
  groupScoreBucketMap: {
    passing: 'Passing',
    rushing: 'Rushing',
    receiving: 'Receiving',
    fieldGoal: 'Field Goal',
    fumble: 'Fumbles Lost',
  },
  groupScoreMap: {
    passing: {
      touchdowns: 'Touchdown',
      yards: 'Pass yds',
      interceptions: 'Interception',
      attempts: 'Attempt',
      completions: 'Completion',
      plays20Plus: '20+ Plays',
      plays40Plus: '40+ Plays',
      twoPointMade: '2PT Pass',
    },
    rushing: {
      attempts: 'Attempt',
      yards: 'Rush yd',
      touchdowns: 'Rush TD',
      plays20Plus: '20-39 Rush',
      plays40Plus: '40+ Rush',
      fumbles: 'Fumbles',
      twoPointMade: '2PT Rush',
    },
    receiving: {
      targets: 'Target',
      receptions: 'Reception',
      yards: 'Rec yd',
      touchdowns: 'Rec TD',
      plays20Plus: '20-39 Rec',
      plays40Plus: '40+ Rec',
      fumbles: 'Rec Fumble',
      twoPointMade: '2PT Rec',
    },
    fumble: {
      fumblesLost: 'Fumble',
    },
    fieldGoal: {
      made1_19: '1-19 yd FG',
      made20_29: '20-29 yd FG',
      made30_39: '30-39 yd FG',
      made40_49: '40-49 yd FG',
      made50Plus: '50+ yd FG',
      extraPointMade: 'Extra Point',
    },
  },
};

const descriptions = {
  bucketDescription: [
    'Passing',
    'Rushing',
    'Receiving',
    'Fumbles Lost',
    'Field Goals',
  ],
  passingDescription: [
    'Pass TD',
    'Yards',
    'Interceptions',
    'Attempts',
    'Completion',
    'Two Point Pass',
  ],
  rushingDescription: [
    'Attempts',
    'Rush Yards',
    'Rush TD',
    '20+ Yard Rush',
    '40+ Yard Rush',
    'Rushing Fumbles',
    'Two Point Rush',
  ],
  receivingDescription: [
    'Target',
    'Receptions',
    'Receiving Yards',
    'Receiving TD',
    '20+ Yard Reception',
    '40+ Yard Reception',
    'Receving Fumble',
    'Two Point Reception',
  ],
  fumbleDescription: ['Fumbles Lost'],
  fieldGoalDescription: [
    '1-19 Yard Field Goal',
    '20-29 Yard Field Goal',
    '30-39 Yard Field Goal',
    '40-49 Yard Field Goal',
    '50+ Yard Field Goal',
    'Extra Point Made',
  ],
};
