import ARILogo from "./logoImages/ARI.png";
import ATLLogo from "./logoImages/ATL.png";
import BALLogo from "./logoImages/BAL.png";
import BUFLogo from "./logoImages/BUF.png";
import CARLogo from "./logoImages/CAR.png";
import CHILogo from "./logoImages/CHI.png";
import CINLogo from "./logoImages/CIN.png";
import CLELogo from "./logoImages/CLE.png";
import DALLogo from "./logoImages/DAL.png";
import DENLogo from "./logoImages/DEN.png";
import DETLogo from "./logoImages/DET.png";
import GBLogo from "./logoImages/GB.png";
import HOULogo from "./logoImages/HOU.png";
import INDLogo from "./logoImages/IND.png";
import JAXLogo from "./logoImages/JAX.png";
import KCLogo from "./logoImages/KC.png";
import LACLogo from "./logoImages/LAC.png";
import LALogo from "./logoImages/LA.png";
import MIALogo from "./logoImages/MIA.png";
import MINLogo from "./logoImages/MIN.png";
import NELogo from "./logoImages/NE.png";
import NOLogo from "./logoImages/NO.png";
import NYGLogo from "./logoImages/NYG.png";
import NYJLogo from "./logoImages/NYJ.png";
import LVLogo from "./logoImages/LV.png";
import PHILogo from "./logoImages/PHI.png";
import PITLogo from "./logoImages/PIT.png";
import SEALogo from "./logoImages/SEA.png";
import SFLogo from "./logoImages/SF.png";
import TBLogo from "./logoImages/TB.png";
import TENLogo from "./logoImages/TEN.png";
import WASLogo from "./logoImages/WAS.png";
import UNKLogo from "./logoImages/UNK.png";

export const ARI = ARILogo;
export const ATL = ATLLogo;
export const BAL = BALLogo;
export const BUF = BUFLogo;
export const CAR = CARLogo;
export const CHI = CHILogo;
export const CIN = CINLogo;
export const CLE = CLELogo;
export const DAL = DALLogo;
export const DEN = DENLogo;
export const DET = DETLogo;
export const GB = GBLogo;
export const HOU = HOULogo;
export const IND = INDLogo;
export const JAX = JAXLogo;
export const KC = KCLogo;
export const LAC = LACLogo;
export const LA = LALogo;
export const MIA = MIALogo;
export const MIN = MINLogo;
export const NE = NELogo;
export const NO = NOLogo;
export const NYG = NYGLogo;
export const NYJ = NYJLogo;
export const LV = LVLogo;
export const PHI = PHILogo;
export const PIT = PITLogo;
export const SEA = SEALogo;
export const SF = SFLogo;
export const TB = TBLogo;
export const TEN = TENLogo;
export const WAS = WASLogo;
export const UNK = UNKLogo;
